TrainingProject/AppOne/urls.py
from django.urls import path
from AppOne import views

#TEMPLATE URLS
app_name = 'AppOne'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
]

TrainingProject/TrainingProject/urls.py
from django.contrib import admin
from django.urls import path, include
from AppOne import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('AppOne/', include('AppOne.urls')),
    path('logout', views.user_logout, name='logout'),

]

TrainingProject/AppOne/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE) #the User class already has some attributes, this will extend the class and add more methods

    additional_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

TrainingProject/AppOne/forms.py
from django import forms
from django.contrib.auth.models import User
from AppOne.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('additional_site','profile_pic')

TrainingProject/AppOne/views.py
from django.shortcuts import render
from AppOne.forms import UserForm, UserProfileForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'AppOne/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method=="POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'AppOne/registration.html', {'user_form':user_form,
                                                        'profile_form':profile_form,
                                                        'registered':registered})

def user_login(request):
    if request.method=="POST":
        username = request.POST.get('username') #'username' was defined in the login form
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and they failed")
            print("Username: {} and password {}".format(username, password))
            return HttpResponse("invalid login details supplied")
    else:
        return render(request, 'AppOne/login.html', {})

TrainingProject/templates/AppOne/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li> <a class="navbar-brand" href="{% url 'index' %}">HOME</a> </li>
          <li> <a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a> </li>
          <li> <a class="navbar-link" href="{% url 'AppOne:register' %}">REGISTER</a> </li>

{% if user.is_authenticated %}

<li> <a class='navbar-link' href="{% url 'logout' %}">Logout</a> </li>

{% else %}
<li> <a class='navbar-link' href="{% url 'AppOne:user_login' %}">Login</a> </li>

{% endif %}

        </ul>
      </div>
    </nav>

    <div class="">
    {% block body_block %}
    {% endblock %}
    </div>

  </body>
</html>

TrainingProject/templates/AppOne/index.html
{% extends "AppOne/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>WELCOME TO THE HOMEPAGE</h1>
</div>

{% endblock %}

TrainingProject/templates/AppOne/login.html
{% extends 'AppOne/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>PLEASE LOGIN</h1>
  <form action="{% url 'AppOne:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">

  </form>

</div>


{% endblock %}

TrainingProject/templates/AppOne/other.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>OTHER PAGE</title>
  </head>
  <body>

  </body>
</html>

TrainingProject/templates/AppOne/registration.html
{% extends "AppOne/base.html" %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registering</h1>
  {% else %}
    <h1>Register Here</h1>
    <h2>Fill out the form below</h2>

    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">      
    </form>

  {% endif %}

</div>

{% endblock %}